### ISSUE TITLE
Does pytorch-stream-dataloader support Multi-GPU ?

### ISSUE THREAD

**Issue by kaixinbear** [etienne87/pytorch-stream-dataloader#7]
Thanks for your great work!
I wonder if this repo supports multi-gpu. In other words, is distribution training supportted?

**Comment by etienne87** [comment]
I have not tried so probably not. Could you provide a minimal code to try out? (text or video ...).

**Comment by kaixinbear** [comment]
Close since I find the solution.

**Comment by etienne87** [comment]
can you share the solution? :-p

**Comment by kaixinbear** [comment]
If we want to use multi-gpu and make the data iterable, just rerank the data for each gpu.
For example,
```
rank = get_rank()
idx = range(len(dataset))[rank:len(len(dataset)):gpu_nums]
fetch_data(dataset, idx)
```
